### ISSUE TITLE
Problem with Android 10: 'struct.error: argument out of range'

### ISSUE THREAD

**Issue by viktorxda** [marin-m/vmlinux-to-elf#19]
Hello, there is unfortunately an issue with some android 10 kernels:
```
[+] Version string: Linux version 4.14.117-perf+ (OnePlus@rd-build-91) (clang version 8.0.8 for Android NDK) #1 SMP PREEMPT Mon Sep 7 21:07:28 CST 2020
[+] Guessed architecture: aarch64 successfully in 13.89 seconds
[+] Found relocations table at file offset 0x1c63128 (count=107056)
[+] Found kernel text candidate: 0xffffff8008080000
Traceback (most recent call last):
  File "/home/itz63c/dumpyara/vmlinux-to-elf/vmlinux_to_elf/kallsyms_finder.py", line 1102, in <module>
    kallsyms = KallsymsFinder(obtain_raw_kernel_from_file(kernel_bin.read()), args.bit_size)
  File "/home/itz63c/dumpyara/vmlinux-to-elf/vmlinux_to_elf/kallsyms_finder.py", line 188, in __init__
    self.apply_elf64_rela()
  File "/home/itz63c/dumpyara/vmlinux-to-elf/vmlinux_to_elf/kallsyms_finder.py", line 356, in apply_elf64_rela
    img[offset:offset+8] = pack('<Q', value)
struct.error: argument out of range
```

Kernel download: [boot.img](https://github.com/itz63c/oneplus_oneplus7t_dump/raw/hotdogb-user-10-QKQ1.190716.003-2009072019-release-keys/boot.img)

**Comment by marin-m** [comment]
Hello,
@screwer 
@Apoch-zxv 
This seems to be related to your successive changes in issues #14 and #18, any clue?
