### ISSUE TITLE
ValueError for kernel 5.4

### ISSUE THREAD

**Issue by jqhong** [marin-m/vmlinux-to-elf#31]
Hello, 
I was trying to recover an ELF file with symbols from a stripped vmlinux. The vmlinux file is at https://drive.google.com/file/d/1crKV7X6wYkGTzUNYd2U9SivjftpIVNKN/view?usp=sharing 
It is is extracted from vmlinuz using extract-vmlinux.sh from kernel tree. 

The error message is as below: 
```
 [+] Found kallsyms_offsets at file offset 0x01368860
Traceback (most recent call last):
  File "/usr/local/bin/vmlinux-to-elf", line 67, in <module>
    args.base_address, args.file_offset
  File "/usr/local/lib/python3.6/dist-packages/vmlinux_to_elf/elf_symbolizer.py", line 44, in __init__
    kallsyms_finder = KallsymsFinder(file_contents, bit_size)
  File "/usr/local/lib/python3.6/dist-packages/vmlinux_to_elf/kallsyms_finder.py", line 216, in __init__
    self.parse_symbol_table()
  File "/usr/local/lib/python3.6/dist-packages/vmlinux_to_elf/kallsyms_finder.py", line 1068, in parse_symbol_table
    symbol.symbol_type = KallsymsSymbolType(symbol_name[0].upper())
  File "/usr/lib/python3.6/enum.py", line 293, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.6/enum.py", line 535, in __new__
    return cls._missing_(value)
  File "/usr/lib/python3.6/enum.py", line 548, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: '_' is not a valid KallsymsSymbolType

```

Could you help to give some hints about the above Error? 
Thanks!

**Comment by marin-m** [comment]
Hello,

Thank you for reporting! I have pushed a fix in commit 1e900f6. You can reinstall or redownload the tool in order to have it fixed.

Regards,
