### ISSUE TITLE
Any way to detect disabled CONFIG_KALLSYMS in kernel

### ISSUE THREAD

**Issue by DrRamm** [marin-m/vmlinux-to-elf#6]
By the way, is there any way to detect disabled CONFIG_KALLSYMS in kernel? I faced with kernel, which allows extract kallsyms from your excellent tool, not as proc/kallsyms, but when I try open elf or use kallsyms from kallsyms_finder (thanks for https://github.com/marin-m/vmlinux-to-elf/commit/7a9ef404bc2408be306cca50e07ff61bcfc7239e) - I can't reverse any function in kernel. A lot of jumpouts. Hope you understood my explanation. Thank you for your work.

**Comment by DrRamm** [comment]
[+] Kernel successfully decompressed in-memory (the offsets that follow will be given relative to the decompressed binary)
[+] Version string: Linux version 3.18.19 (kotsareu@kotsareu) (gcc version 4.8 (GCC) ) #1 SMP PREEMPT Sun Jan 5 15:00:51 MSK 2020
[+] Guessed architecture: armle successfully in 1.9759182929992676 seconds
Traceback (most recent call last):
  File "/vmlinux-to-elf/vmlinux_to_elf/kallsyms_finder.py", line 193, in __init__
    self.find_kallsyms_names_uncompressed()
  File "/vmlinux-to-elf/vmlinux_to_elf/kallsyms_finder.py", line 417, in find_kallsyms_names_uncompressed
    raise KallsymsNotFoundException('No embedded symbol table found in this kernel')
kallsyms_finder.KallsymsNotFoundException: No embedded symbol table found in this kernel
